version: '3.9'

services:
  web:
    image: alaamuhissen/recognize_clothes_and_colors_api:latest
    container_name: recognize_clothes_and_colors_api_container
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8180:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
