name: Trigger Webhook on Prod Push

on:
  push:
    branches:
      - production

jobs:
  push_to_prod:
    timeout-minutes: 100
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Send webhook to server
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" -X POST "https://github.jce.ac/webhook/8de4b659-3610-4399-af65-b8ecf1700a08")
          if [ $response -ne 200 ]; then
            echo "Webhook call failed with status $response"
            exit 1
          else
            echo "Webhook call succeeded with status $response"
          fi
